ace:
  arch: [ace]
  debian: [libace-dev]
  gentoo: [dev-libs/ace]
  ubuntu: [libace-dev]
ack-grep:
  arch: [ack]
  debian: [ack-grep]
  fedora: [ack]
  gentoo: [sys-apps/ack]
  ubuntu: [ck-grep]
acpi:
  debian: [acpi]
  fedora: [acpi]
  gentoo: [sys-power/acpi]
  ubuntu: [acpi]
kernel:
  debian: [kernel]
