name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/labeler
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
